name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: trampfox/dam-playground:latest
          context: .
          file: ./docker/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
